### ISSUE TITLE
Can't commit?

### ISSUE THREAD

**Issue by Drakonnaskaiba** [cejones9/Prioritize#12]
I've done some editing of the Progress Report, but when I try to upload the file, it freezes and won't let me upload. Any idea what to do?

**Comment by cejones9** [comment]
Just tested. and it worked for me. If you don't get it fixed share the report with us on Google Docs

**Comment by Drakonnaskaiba** [comment]
Okay, I'll try again. Just give me a few mins.

**Comment by Drakonnaskaiba** [comment]
Fixed.
