### ISSUE TITLE
Adding Reminder:

### ISSUE THREAD

**Issue by cejones9** [cejones9/Prioritize#17]
When a reminder is created it is saved into the SQLite Database and in a JSON file.

SQLite query  example: 
INSERT into Reminder 
(A1, Thaw out the chicken, 3/13/17, NULL, Calculated Date, Calculated Time, F, F, 0)

**Comment by cejones9** [comment]
SQLite portion is complete.

**Comment by Drakonnaskaiba** [comment]
JSON portion is complete.
