### ISSUE TITLE
JSON - Getting information

### ISSUE THREAD

**Issue by Drakonnaskaiba** [cejones9/Prioritize#20]
Shahrukh - When you create the reminder, do you have methods for me to call so that I can get the information to convert to a JSON format?

**Comment by cejones9** [comment]
Download and open the GUI as a new project on Android Studio. It's in the addAlarm activity.  That's also where your code for this is going to go, so you can just take values from there

**Comment by Drakonnaskaiba** [comment]
I've been having trouble getting the virtualization running and enabled on my PC, having difficulty finding the location within the BIOS. I've checked a few times, and I'm not sure what I'm missing. I'll keep looking though. For now, I uploaded a file with a basic JSON converter. Take a look and let me know what you think. 

Thanks! ^_^

**Comment by Drakonnaskaiba** [comment]
JSON is completed.
