### ISSUE TITLE
Synch between devices

### ISSUE THREAD

**Issue by Drakonnaskaiba** [cejones9/Prioritize#6]
If we are to implement an ability to synch between android devices, we need to have a database that will hold the information. We should decide what that information is, as well as what kind of database we need to use. 

Also, if we're dealing with this, I would like to implement some sort of encryption and security features to the application as well, to try to make things more secure. If we do choose to implement a database, then we won't need the reminder object, so instead, I can work on the security features. I would prefer that, to be perfectly honest.

**Comment by ghost** [comment]
We still need the reminder object so user can view all the reminders without having to sync over and over again. Syncing should be used only if user wants to view the reminders on another device.

**Comment by Drakonnaskaiba** [comment]
I think Google Drive API will allow us to do this. I need to research more into how that works, etc.

**Comment by cejones9** [comment]
Reminders are held in a sqlite database. When they first use the app they are offered the ability to sync, they can say no or they can say yes. The Google Drive folder works as if it's an offline folder, we will just send information there, whenever there is a connection then it's synced with the online cloud and available to other devices. After significant testing I've come up with two solutions two this. they are going in a doc on the docs section

**Comment by Drakonnaskaiba** [comment]
Perfect. Thanks, Cody.
