### ISSUE TITLE
Progress Report  / Presentation 3 (Due 2/28)

### ISSUE THREAD

**Issue by Drakonnaskaiba** [cejones9/Prioritize#7]
I want to start working on this next Progress Report next week. We don't have to finish it, but I want to start working on it, and polish as much as we can before we have to present.

**Comment by ghost** [comment]
We should meet once a week out of the class or plan out something similar so we can keep up with all our progress. Right now we're working individually for the most part.

**Comment by Drakonnaskaiba** [comment]
Agreed. That'd be good. I'm open Tuesday and Thursday after class, and Monday Wednesday from 11:30-3:00. I'm tutoring in the lab at those times, so I may have to go help other students, but it's generally quiet.

**Comment by Drakonnaskaiba** [comment]
Done.
