### ISSUE TITLE
Individual work updates 

### ISSUE THREAD

**Issue by Drakonnaskaiba** [cejones9/Prioritize#9]
How is your individual work going? Please let us know here what you've been working on, and how you're making progress. 

For the time picker, what is the format you're using to keep track of the day? Is it just a simple DD/MM/YYYY string? As for time, how have you denoted that? 

What about the reminders? How is that progressing? 

As for the GUI, do you have any screenshots yet of what you've gotten done?

Thanks guys!

**Comment by Drakonnaskaiba** [comment]
Respond, please.

**Comment by cejones9** [comment]
I didn't see this till now that's my bad. Tomorrow I'm gonna get a design for Google drive made and tested out and finished tomorrow.

**Comment by Drakonnaskaiba** [comment]
No longer need this issue.
